name: Deploy Backend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file backend/cloudformation/decodedMusicBackend.yaml \
            --stack-name DecodedMusicBackend \
            --region eu-central-1 \
            --capabilities CAPABILITY_NAMED_IAM
